name: Build and Test Java Library

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: aarch64
          - os: ubuntu-latest
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: gradle

      - name: Build and publish crud_jt-java to Maven local
        run: ./gradlew publishToMavenLocal

      - name: Run tests in the test project
        working-directory: ./test
        run: ./gradlew run
